name: My-GitHub-Actions
env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask_deploy_ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - master

jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello Testing
      run: echo "Hello World form Testing job"
    - name: Execute few commands
      run: |
        echo "Hello message 1"
        echo "Hello message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
  
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
    - name: Print hello Deploy
      run: echo "Hello world from Deploy job"
    - name: Printing Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
  
