name: My-GitHub-Actions

on: 
  push:
    branches: 
      - master

jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello Testing
      run: echo "Hello World form Testing job"
  
  my-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello Deploy
      run: echo "Hello world from Deploy job"