name: My-GitHub-Actions
env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask_deploy_ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - master

jobs:
  my-testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print hello Testing
      run: echo "Hello World form Testing job"
    - name: Execute few commands
      run: |
        echo "Hello message 1"
        echo "Hello message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
    - name: List current folder
      run : ls -la
    
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: List current folder 2
      run : ls -la
  
  my-deploy:
    env:
      VAR1: "This is Job level variable 1"
      VAR2: "This is Job level variable 2"

    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
    - name: Print hello Deploy
      run: echo "Hello world from Deploy job"

    - name: Print env vars
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "Var3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is Super local ENV"

    - name: Printing Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"

    - name: Lets test some packages if the are here 1
      run: aws --version

    - name: Lets test some packages if the are here 2
      run: zip --version
  
